### PR TITLE
drop deprecated settings

### LINKED ISSUE #928: drop deprecated settings

### PR DESCRIPTION
**Pull request by pamapa**
Closes/fixes #928 and #825

### Checklist

- [x] This PR makes changes to the public API 
- [x] I have included links for closing relevant issue numbers

### CODE REVIEW

**Comment by deanmaster** [comment]
hi @pamapa do you have draft timeframe when 3.0.0 will be released. I just would like to align a bit of planning about this.

**Comment by pamapa** [comment]
@deanmaster i plan the 3.0.0 for the end of January. I have not received much feedback and there is only one merge request (#1313) open, that i want to land first....

**Comment by pamapa** [comment]
@deanmaster Please give [v3.0.0-rc.1](https://github.com/authts/oidc-client-ts/commit/adfa729cc9574445403a6cd7fcb28d9e7c939bf8) a try, it will be more or less the same, except bug-fixing...

**Comment by deanmaster** [comment]
hi @pamapa thanks I will plan for now in  end of January.

**Pull request merged**
