### PR TITLE
fix: return signout response from signoutCallback

### PR DESCRIPTION
**Pull request by dopry**
this is a backport to the 2.4.x series of https://github.com/authts/oidc-client-ts/pull/1672,  but a branch doesn't exist for me to open a PR against. 

### Checklist

- [ ] This PR makes changes to the public API 
- [ ] I have included links for closing relevant issue numbers

### CODE REVIEW

**Comment by pamapa** [comment]
created `release/2.4.x` branch for backports

**Comment by dopry** [comment]
@pamapa  thanks!

**Comment by pamapa** [comment]
please rebase against release/v2 latest, the CI did not trigger, which i have fixed now #1686

**Comment by dopry** [comment]
@pamapa done!

**Comment by pamapa** [comment]
thanks for contributing

**Pull request merged**
