### PR TITLE
add sourcemaps

### PR DESCRIPTION
**Pull request by pamapa**
i have now removed the x.esm.js rename, its not needed

### CODE REVIEW

**Review by kherock — APPROVED** [review]
I believe this exports configuration should fix webpack 4 compatibility. I'll open a similar PR in react-oidc-context and see if it works in my CRA workspace.

**Comment by kherock** [comment]
other PR here: https://github.com/authts/react-oidc-context/pull/139

I've included a sample repo there if you want to test it yourself before releasing.

**Comment by pamapa** [comment]
This works fine here, but notice that somehow here the mjs extension is working with webpack v4. Thus we are open to change this or keep it as it is.

**Comment by pamapa** [comment]
BTW: as this is my merge request i can not approve your changes in the GUI dialog, but consider them approved by this comment.

**Comment by kherock** [comment]
I actually couldn't get it working for me without these changes on my CRA workspace. When I fix the exports for `react-oidc-context`,  I end up getting

```
Attempted import error: 'UserManager' is not exported from 'oidc-client-ts'.
```

**Pull request merged**
